# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import user_pb2 as user__pb2


class UsuarioServicioStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/user.UsuarioServicio/GetUser',
                request_serializer=user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserReply.FromString,
                )
        self.ProcessImage = channel.unary_unary(
                '/user.UsuarioServicio/ProcessImage',
                request_serializer=user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserReply.FromString,
                )
        self.GetStreamImage = channel.stream_unary(
                '/user.UsuarioServicio/GetStreamImage',
                request_serializer=user__pb2.GetImage.SerializeToString,
                response_deserializer=user__pb2.GetUserReply.FromString,
                )
        self.ImageStreamReply = channel.stream_stream(
                '/user.UsuarioServicio/ImageStreamReply',
                request_serializer=user__pb2.GetImage.SerializeToString,
                response_deserializer=user__pb2.GetImageReply.FromString,
                )
        self.GetUserBidiStream = channel.stream_stream(
                '/user.UsuarioServicio/GetUserBidiStream',
                request_serializer=user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user__pb2.GetAllReply.FromString,
                )


class UsuarioServicioServicer(object):
    """The greeting service definition.
    """

    def GetUser(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImageStreamReply(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBidiStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioServicioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=user__pb2.GetUserRequest.FromString,
                    response_serializer=user__pb2.GetUserReply.SerializeToString,
            ),
            'ProcessImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessImage,
                    request_deserializer=user__pb2.GetUserRequest.FromString,
                    response_serializer=user__pb2.GetUserReply.SerializeToString,
            ),
            'GetStreamImage': grpc.stream_unary_rpc_method_handler(
                    servicer.GetStreamImage,
                    request_deserializer=user__pb2.GetImage.FromString,
                    response_serializer=user__pb2.GetUserReply.SerializeToString,
            ),
            'ImageStreamReply': grpc.stream_stream_rpc_method_handler(
                    servicer.ImageStreamReply,
                    request_deserializer=user__pb2.GetImage.FromString,
                    response_serializer=user__pb2.GetImageReply.SerializeToString,
            ),
            'GetUserBidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetUserBidiStream,
                    request_deserializer=user__pb2.GetUserRequest.FromString,
                    response_serializer=user__pb2.GetAllReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.UsuarioServicio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UsuarioServicio(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.UsuarioServicio/GetUser',
            user__pb2.GetUserRequest.SerializeToString,
            user__pb2.GetUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.UsuarioServicio/ProcessImage',
            user__pb2.GetUserRequest.SerializeToString,
            user__pb2.GetUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStreamImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/user.UsuarioServicio/GetStreamImage',
            user__pb2.GetImage.SerializeToString,
            user__pb2.GetUserReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImageStreamReply(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/user.UsuarioServicio/ImageStreamReply',
            user__pb2.GetImage.SerializeToString,
            user__pb2.GetImageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserBidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/user.UsuarioServicio/GetUserBidiStream',
            user__pb2.GetUserRequest.SerializeToString,
            user__pb2.GetAllReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
