# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\":\n\x0eGetUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pow\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\x0c\"7\n\x0bGetAllReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03pow\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\x0c\"\x1f\n\x0cGetUserReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x08GetImage\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1e\n\rGetImageReply\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\xc1\x02\n\x0fUsuarioServicio\x12\x35\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x12.user.GetUserReply\"\x00\x12:\n\x0cProcessImage\x12\x14.user.GetUserRequest\x1a\x12.user.GetUserReply\"\x00\x12\x38\n\x0eGetStreamImage\x12\x0e.user.GetImage\x1a\x12.user.GetUserReply\"\x00(\x01\x12=\n\x10ImageStreamReply\x12\x0e.user.GetImage\x1a\x13.user.GetImageReply\"\x00(\x01\x30\x01\x12\x42\n\x11GetUserBidiStream\x12\x14.user.GetUserRequest\x1a\x11.user.GetAllReply\"\x00(\x01\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_GETUSERREQUEST']._serialized_start=20
  _globals['_GETUSERREQUEST']._serialized_end=78
  _globals['_GETALLREPLY']._serialized_start=80
  _globals['_GETALLREPLY']._serialized_end=135
  _globals['_GETUSERREPLY']._serialized_start=137
  _globals['_GETUSERREPLY']._serialized_end=168
  _globals['_GETIMAGE']._serialized_start=170
  _globals['_GETIMAGE']._serialized_end=195
  _globals['_GETIMAGEREPLY']._serialized_start=197
  _globals['_GETIMAGEREPLY']._serialized_end=227
  _globals['_USUARIOSERVICIO']._serialized_start=230
  _globals['_USUARIOSERVICIO']._serialized_end=551
# @@protoc_insertion_point(module_scope)
